<?php $buttons = $this->element->getButtons(); ?>
<?php if ($buttons && is_array($buttons)) :?>
    <?php foreach ($buttons as $key => $button): ?>
        <?php $resource = isset($button['resource']) ? $button['resource'] : null; ?>
        <?php $action   = isset($button['action']) ? $button['action'] : null; ?>
        <?php $acl      = isset($resource) && isset($action); ?>
        <?php $btnClass = isset($button['btnClass']) ? $button['btnClass'] : 'primary'; ?>
        <?php $click    = isset($button['click']) ? 'data-ng-click="' . $button['click'] . '"' : ''; ?>
        <?php $text     = isset($button['btnText']) ? $button['btnText'] : 'Click Here'; ?>
        <?php $attrs    = isset($button['attributes']) ? $button['attributes'] : ''; ?>
        <?php if (!$acl || $this->isAllowed($resource, $action)): ?>
            <button <?php echo $click; ?> class="button <?php echo $btnClass; ?>" type="button" <?php echo $attrs; ?>><?php echo $this->translate($text); ?></button>
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif;?>