<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'FzyForm\Annotation\Element'             => __DIR__ . '//src/FzyForm/Annotation/Element.php',
  'FzyForm\Annotation\Field'               => __DIR__ . '//src/FzyForm/Annotation/Field.php',
  'FzyForm\Annotation\FieldSet'            => __DIR__ . '//src/FzyForm/Annotation/FieldSet.php',
  'FzyForm\Annotation\Field\Checkbox'      => __DIR__ . '//src/FzyForm/Annotation/Field/Checkbox.php',
  'FzyForm\Annotation\Field\MultiCheckbox' => __DIR__ . '//src/FzyForm/Annotation/Field/MultiCheckbox.php',
  'FzyForm\Annotation\Field\Radio'         => __DIR__ . '//src/FzyForm/Annotation/Field/Radio.php',
  'FzyForm\Annotation\Field\Select'        => __DIR__ . '//src/FzyForm/Annotation/Field/Select.php',
  'FzyForm\Annotation\Field\Wysiwyg'       => __DIR__ . '//src/FzyForm/Annotation/Field/Wysiwyg.php',
  'FzyForm\Annotation\Form'                => __DIR__ . '//src/FzyForm/Annotation/Form.php',
  'FzyForm\Annotation\Row'                 => __DIR__ . '//src/FzyForm/Annotation/Row.php',
  'FzyForm\Annotation\Subform'             => __DIR__ . '//src/FzyForm/Annotation/Subform.php',
  'FzyForm\Module'                         => __DIR__ . '//Module.php',
  'FzyForm\View\Helper\FzyForm'            => __DIR__ . '//src/FzyForm/View/Helper/FzyForm.php',
);
