<?php
if ($this->element) {
	/* @var $element \FzyForm\Annotation\Field */
	$element = $this->element;
	if (!$element->getNoLabel()) {
		echo $this->partial($element->getLabelTemplate(), array('element' => $element));
	}
	echo $this->partial($element->getInputTemplate(), array('element' => $element));
    echo $this->partial($element->getHelpTemplate(), array('element' => $element));
    echo $this->partial($element->getErrorTemplate(), array('element' => $element));
}
