<?php if ($this->element): ?>
    <?php /* @var $element \FzyForm\Annotation\FieldSet */ ?>
    <?php $element = $this->element; ?>
	<div class="fieldset">
		<fieldset>
			<?php if ($element->getLegend()) :?>
			    <legend><?php echo $element->getLegend(); ?></legend>
            <?php endif; ?>
            <?php echo $this->partial('fzyform/form/children', array('element' => $this->element, 'scope' => $this->scope, 'subform' => $this->subform)); ?>
		</fieldset>
	</div>
<?php endif; ?>
